name: server-workflow

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

defaults:
  run:
    working-directory: server

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: JDK 21을 설치합니다
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Gradle 명령 실행을 위한 권한을 부여합니다
      run: chmod +x gradlew

    - name: Gradle build를 수행합니다
      run: ./gradlew clean build

    - name: 테스트 결과를 작성합니다
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/build/test-results/test/TEST-*.xml'

    - name: 테스트가 실패한 위치에 코멘트를 작성합니다
      uses: mikepenz/action-junit-report@v4
      if: failure()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
